// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CharacterWriteRepository is an autogenerated mock type for the CharacterWriteRepository type
type CharacterWriteRepository struct {
	mock.Mock
}

// StoreByID provides a mock function with given fields: ctx, id
func (_m *CharacterWriteRepository) StoreByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreByPage provides a mock function with given fields: ctx, page
func (_m *CharacterWriteRepository) StoreByPage(ctx context.Context, page int) error {
	ret := _m.Called(ctx, page)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
