version: '3'

services:
  app:
    image: golang:1.16.6
    command: ["sh", "-c", "go build -o bin/ cmd/main.go && ./bin/main"]
    ports:
      - 8080:8080
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - home:/root
      - gocache:/go
      - .:/app

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      API_URL: 'openapi/swagger.yaml'
      PORT: 3000
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/openapi/swagger.yaml
    ports:
      - 3000:3000
  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  home:
  gocache:
  redis-data:
